services:
  postgres:
    image: postgres:latest
    container_name: postgres_email_service
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      TZ: America/Sao_Paulo
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email_service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?schema=public
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9000:9000"

volumes:
  postgres_data:
