services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: emailService
      PGDATA: /var/lib/postgresql/data
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email_service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://root:root@postgres:5432/emailService"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
