services:
  postgres:
    image: postgres
    container_name: postgres_email_service
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: emailService
      PGDATA: /data/postgres
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres_data: