version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_email_service
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email_service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
